### GET /
GET http://localhost:3000

### Register a user POST /AUTH/REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "gillit@gmail.com",
    "password": "password"
}

### Authenticate a user POST /AUTH/LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "gillit@gmail.com",
    "password": "password"
}

### Fetch todo list GET /TODOS/
GET http://localhost:3000/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsImlhdCI6MTczODk2MzgxMywiZXhwIjoxNzM5MDUwMjEzfQ.mPxXr2CYCkfYEYDonXNRExpGK4bgTSaRUkxuUcf9Flo

### Add todo list POST /TODOS/
POST http://localhost:3000/todos/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsImlhdCI6MTczODk2MzgxMywiZXhwIjoxNzM5MDUwMjEzfQ.mPxXr2CYCkfYEYDonXNRExpGK4bgTSaRUkxuUcf9Flo

{
    "task" : "Don't do this task"
}

### Update todo list PUT /TODOS/:ID
PUT http://localhost:3000/todos/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsImlhdCI6MTczODk2MzgxMywiZXhwIjoxNzM5MDUwMjEzfQ.mPxXr2CYCkfYEYDonXNRExpGK4bgTSaRUkxuUcf9Flo

{
    "task" : "Don't do this task",
    "completed" : "1"
}

### Delete from todo list DELETE /TODOS/:ID
DELETE http://localhost:3000/todos/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsImlhdCI6MTczODk2MzgxMywiZXhwIjoxNzM5MDUwMjEzfQ.mPxXr2CYCkfYEYDonXNRExpGK4bgTSaRUkxuUcf9Flo
