### GET /
GET http://localhost:3000

### Register a user POST /AUTH/REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "gillt@gmail.com",
    "password": "password"
}

### Authenticate a user POST /AUTH/LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "gillt@gmail.com",
    "password": "password"
}

### Fetch todo list GET /TODOS/
GET http://localhost:3000/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4ODYzMDMxLCJleHAiOjE3Mzg5NDk0MzF9.78QtC2sj787-GNlqmW_q9RlOyVcpOXC6Rlym91jwBGU

### Add todo list POST /TODOS/
# POST http://localhost:3000/todos/
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4ODYzMDMxLCJleHAiOjE3Mzg5NDk0MzF9.78QtC2sj787-GNlqmW_q9RlOyVcpOXC6Rlym91jwBGU

# {
#     "task" : "Don't do this task"
# }